apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: java-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        node-type: redis
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        # 👇 Redis default port - no username/password needed
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP